namespace GameManagement
{
    public enum CheckpointReason
    {
        MenuEntered,
        SkinPurchased,
        SkinApplied,
        SuperAttackSelected,
        QuestCompleted,
        QuestProgressed,
        QuestRewardClaimed,
        DailyQuestSetRotated,
        WeeklyLeaderboardRecordRewarded,
        LevelCompleted,
        CurrentLevelChanged,
        TutorialCompleted,
        AccountPromptStateChanged,
        AccountLinked,
        AppBackgrounded,
        StoryQuestSetChanged,
        DailyQuestCommonRewardClaimed,
        DeveloperResourceGranted,
        CharacterDevelopmentUnlocked,
        RewardedAdIntentRecorded,
        RewardedAdRewardGranted,
        ShopItemPurchased,
        WeeklyLeaderboardRunQueued
    }
}
